### ISSUE TITLE
Issue doesn't get flagged again when issue is made invalid

### ISSUE THREAD

**Issue by whitep4nth3r** [nordcraftengine/nordcraft#435]
Steps to reproduce:

1. Add img tag
2. Observe issue for missing height/width attributes
3. Add height/width attributes
4. Observe issue disappear
5. Remove height/width attributes
6. Observe issue does NOT reappear

**Comment by erik-beus** [comment]
@jacob-kofoed could you investigate this when you have time? 🤞

**Comment by whitep4nth3r** [comment]
So there's a different issue now.

I add an img tag and it comes with blank src and alt attributes, but the issues panel shows "missing src and alt". "alt" can be blank if used for presentational purposes, and given the src and alt are there when you add an image, we shouldn't flag those straight away.

The initial bug is fixed though, as when I delete the height/width attributes, the issues get flagged again.

However, I don't think we should flag attributes that exist, but just don't have a value.

Also, the issue flags are inconsistent.

If I add a height/width attribute, but leave them blank, the issues are not present. But for blank src and alt, the issues ARE present.

<img width="2319" height="1403" alt="Image" src="https://github.com/user-attachments/assets/45eb539b-9785-4018-bc47-108daa162d7f" />

**Comment by cullophid** [comment]
If we are saying that all images should have an alt attribute, I don't think  removing it by default makes much sense.

I also don't think the alt attribute should ever be empty.

<img width="744" height="544" alt="Image" src="https://github.com/user-attachments/assets/b3f478c4-4952-479a-a225-598668231b77" />

Images with an empty alt text still show up in the accessibility tree. I think it would make sense to change the alt rule to also look for aria-hidden=true.
 
As for width and height it is also a bit more complex: We need the image aspect ratio which can either come from the width / height attributes, width height css properties or the aspect ratio property. 

The rule we have now is pretty good, the only changes I would do is to check that the width and height values are not empty, and that css height or width is not auto.

**Comment by cullophid** [comment]
I have created two separate issues for these:
https://github.com/orgs/nordcraftengine/projects/19/views/1?pane=issue&itemId=135593477&issue=nordcraftengine%7Cnordcraft-internal%7C3381

and 

https://github.com/orgs/nordcraftengine/projects/19/views/1?pane=issue&itemId=135593319&issue=nordcraftengine%7Cnordcraft-internal%7C3380
